# Generated by Django 4.2.5 on 2023-09-30 18:33

from django.db import migrations

def populate_role(apps, schemaeditor):
    entries = {
        "developer": "A person tasked with completing issuse",
        "Scrum master": "The development team's coach",
        "product owner": "A team member who defines tasks",
    }
    Role = apps.get_model("accounts", "Role")
    for key, value in entries.items():
        role_obj = Role(name=key, description=value)
        role_obj.save()

def populate_team(apps, schemaeditor):
    entries = {
        "alpha": "The A team",
        "brovo": "The B team",
        "charlie": "The C team",
        "delta": "The D team",
    }
    Team = apps.get_model("accounts", "Team")
    for key, value in entries.items():
        team_obj = Team(name=key, description=value)
        team_obj.save()

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue that has not yet been started",
        "in progress": "An issue for which work has not yet been started",
        "done": "An issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', "issues", '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_role),
        migrations.RunPython(populate_team),
        migrations.RunPython(populate_status)
    ]
